// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebProject.Models;

namespace TestWebProject.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20210819155219_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("TestWebProject.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressRecipient")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("CargoWeight")
                        .HasColumnType("INT(11)");

                    b.Property<DateTime>("DateOfReceiving")
                        .HasColumnType("DATE");

                    b.Property<string>("RecipientСity")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("SenderСity")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
